fun main() {
    print("Student Enrollment No.:")
    var en  = readln()
    print("Student Name:")
    var n = readln()
    print("Student Branch:")
    var br = readln()
    print("Student Class:")
    var c = readln()
    print("Student Batch:")
    var batch = readln()
    print("Student College Name:")
    var cn = readln()
    print("Student University Name:")
    var Un = readln()
    print("Student Age:")
    var Age = readln()

    println("*******************")
    println()
    println("Student's Data:")
    println("Enrollment No.: ${en}")
    println("Name: $n")
    println("Age: ${Age.toInt()}")
    println("Branch: $br")
    println("Class: $c")
    println("Batch: $batch")
    println("College Name: $cn")
    println("University Name: $Un")
}